### ISSUE TITLE
About anomaly-guided: ModuleNotFoundError: No module named 'gan_and_str'

### ISSUE THREAD

**Issue by smallrookie** [YangjiaqiDig/OCT_Retinal_Project#1]
About anomaly-guided: ModuleNotFoundError: No module named 'gan_and_str'

**Comment by YangjiaqiDig** [comment]
@smallrookie  Hey sorry just saw your message. I just pushed the folder (it was in my ignore file.. and the code is originally from GANomaly repo: https://github.com/samet-akcay/ganomaly) 
I have the pretrained GANomaly model on OCT healthy images, will upload it with the data soon. thank you for your interest

**Comment by smallrookie** [comment]
> @smallrookie Hey sorry just saw your message. I just pushed the folder (it was in my ignore file.. and the code is originally from GANomaly repo: https://github.com/samet-akcay/ganomaly) I have the pretrained GANomaly model on OCT healthy images, will upload it with the data soon. thank you for your interest

ok, thanks
