### ISSUE TITLE
Missing resc_cls_labels.npy file

### ISSUE THREAD

**Issue by awmirz** [YangjiaqiDig/OCT_Retinal_Project#2]
There is a missing file within the datasets.tar.gz file.

```
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/RESC/resc_cls_labels.npy'
```

**Comment by YangjiaqiDig** [comment]
> There is a missing file within the datasets.tar.gz file.
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'datasets/RESC/resc_cls_labels.npy'
> ```

@awmirz  Thanks for pointing this out! this file was generated based on the labels from the dataset for convenient loading. I just uploaded that file in the google drive, please put it into the RESC dataset folder, thank you!
